MODELS_PATH: "/home/taoxinhao/CDTNet-High-Resolution-Image-Harmonization/models"
EXPS_PATH: "/home/taoxinhao/CDTNet-High-Resolution-Image-Harmonization/exps"

HFLICKR_PATH: "/data/caojunyan/datasets/IHD/HFlickr"
HDAY2NIGHT_PATH: "/data/caojunyan/datasets/IHD/Hday2night"
HCOCO_PATH: "/data/caojunyan/datasets/IHD/HCOCO"
HADOBE5K_PATH: "/data/caojunyan/datasets/IHD/HAdobe5k"
CCHARMONY_PATH: "/data/caojunyan/datasets/ccHarmony"
HR_PATH: "/data/caojunyan/datasets/HR"

IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: ""
  HRNETV2_W18: ""
  HRNETV2_W32: ""
  HRNETV2_W40: ""
  HRNETV2_W48: ""
  # HRNETV2_W18_SMALL: "/media/sda/PretrainedModels/hrnet/hrnet_w18_small_model_v2.pth"
  # HRNETV2_W18: "/media/sda/PretrainedModels/hrnet/hrnetv2_w18_imagenet_pretrained.pth"
  # HRNETV2_W32: "/media/sda/PretrainedModels/hrnet/hrnetv2_w32_imagenet_pretrained.pth"
  # HRNETV2_W40: "/media/sda/PretrainedModels/hrnet/hrnetv2_w40_imagenet_pretrained.pth"
  # HRNETV2_W48: "/media/sda/PretrainedModels/hrnet/hrnetv2_w48_imagenet_pretrained.pth"